
CREATE TABLE USER_TABLE (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(40) NOT NULL,
	PASSWORD VARCHAR(60) NOT NULL,
	EMAIL VARCHAR(250) NOT NULL,
	ENABLED TINYINT NOT NULL DEFAULT 1,
	PRIMARY KEY (ID)
	);
	
 