CREATE TABLE CAR_TABLE (
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
MODEL VARCHAR(50) NOT NULL,
BRAND VARCHAR(50) NOT NULL,
MANUFACTURE_YEAR BIGINT(20) NOT NULL,
USER_ID BIGINT(20) NULL DEFAULT NULL,
PRIMARY KEY(ID),
CONSTRAINT FK_SERVICE_CAR_CONSTRAINT FOREIGN KEY(USER_ID) REFERENCES USER_TABLE(ID)
);