CREATE TABLE DEFECTION_TABLE (
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
DESCRIPTION VARCHAR(20) NOT NULL,
APPOINTMENT_DATA VARCHAR(50) NOT NULL,
CAR_ID BIGINT(20) NOT NULL,
PRIMARY KEY(ID),
CONSTRAINT FK_CONSTRAINT_DEFECTION FOREIGN KEY(CAR_ID) REFERENCES CAR_TABLE(ID)
);